# Generated by Django 3.0.8 on 2020-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(help_text='nick', max_length=30),
        ),
    ]
