# Generated by Django 3.0.8 on 2020-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20200723_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
